#!/usr/bin/env python

import rospy
import time
from std_msgs.msg import Float64

def data(jdata1, jdata2):

    j1.data=jdata1
    j2.data=jdata2
    print("hola")
    pub1.publish(j1)
    pub2.publish(j2)

    return 1;


if __name__ == "__main__":

    rospy.init_node("sendJointsGzNode")
    topic1 = '/robotfr/joint4_position_controller/command'
    topic2 = '/robotfr/joint5_position_controller/command'
    pub1 = rospy.Publisher(topic1, Float64, queue_size=10, latch=True)
    pub2 = rospy.Publisher(topic2, Float64, queue_size=10, latch=True)
    
    j1 = Float64()
    j2 = Float64()

    data(0.5, 0.5)
    time.sleep(8)
    data(0.2, 0.2)
    time.sleep(8)
    data(0.6, 0.6)
    
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        rate.sleep()
